<template>
    <div class="home">
    <div>
      <b-row>
        <b-col lg="2"></b-col>
        <b-col lg="8" cols="12" class="form-card p-5 mt-4">
          <h1>This Application Explained</h1>
          <hr>

          <h2>Registration Form</h2>
          <b-alert show>Allows a new user to make a new account and use the application.</b-alert>
          <p>The registration form prompts a new user for several different criteria.  Passwords must pass various utility function conditions to make sure they contain the correct complexity requirements.  Email field is similar, where the field is primitively checked to make sure that it contains an "@" sign to verify it's an attempt at a valid email address.  Bootstrap provides some basic "field required" notifications on submission without a field filled.</p>
          <p>The backend conducts similar checks on submission, while also verifying that user and email address aren't already in use by another user.  Passwords are hashed with Bcrypt and stored hashed inside of the database.</p>
          <p>On succesful return of a registration server response, the user is pushed towards the login screen.</p>

          <h2>Login Form</h2>
          <b-alert show>Allows a user to sign in to the application.</b-alert>
          <p>Similar to the registration form, a user inputs their user login and password against several front end checks to be able to login.  Upon succesful verification of user credentials, a token is signed and given back in a response to the user.  This token is stored in state to be used for all other requests that need authentication.  The user is also pushed to a generic dashboard page that is secured by front end route guards. </p>

          <h2>Forgot Password</h2>
          <b-alert show>Allows a user to send a password reset request to their email address.</b-alert>
          <p>A user enters their email address and a password reset request is sent to their email address entered.  If the email address is not matched to an existing account, the server says so.</p>
          <b-alert variant="warning" show>This initial reset email does not actually reset the password on file, the link generated by the server has to be clicked inside of the email and reset after that.</b-alert>
          <p>Nodemailer sends an email from the backend to the email address entered in the field as a preliminary request for password request.</p>


          <h2>Confirm Password</h2>
          <b-alert show>Sends a confirmation email to the email address stored on registration.  A user must confirm their email address to login</b-alert>
          <p>The backend sends an email using nodemailer and an outlook account to send a confirmation email to the newly registered user.  There is also a feature to resend the confirmation email incase the first one was not clicked.</p>

          <h2>Signout</h2>
          <b-alert show>Allows a user to sign out of the application.</b-alert>
          <p>On signout, the json web token used by the user is blacklisted and the user needs to re-login to get a new token to make more authenticated requests.</p>

          <hr>

          <h2>Front End Technologies used</h2>
          <b-list-group >
            <b-list-group-item>VueJS</b-list-group-item>
            <b-list-group-item>Vuex</b-list-group-item>
            <b-list-group-item>Vue Router</b-list-group-item>
          </b-list-group>
          <h2>Back End Technologies used</h2>
          <b-list-group >
            <b-list-group-item>NodeJS</b-list-group-item>
            <b-list-group-item>ExpressJS</b-list-group-item>
            <b-list-group-item>MongoDB</b-list-group-item>
            <b-list-group-item>Mongoose</b-list-group-item>
            <b-list-group-item>Axios</b-list-group-item>
            <b-list-group-item>JSON Web Token</b-list-group-item>
            <b-list-group-item>Bcrypt</b-list-group-item>
          </b-list-group>
          <br>
          <h3>View the source code on github <a href="http://www.github.com/e-vana">here.</a></h3>




        </b-col>
        <b-col lg="2"></b-col>
      </b-row>
    </div>



  
  </div>
</template>

<script>
export default {
  Name: 'Breakdown'
}
</script>

<style>

</style>